$(document).ready(function(){
  $(".img_1").click(function(){
    $(this).toggle(function(){
      $(".design").toggle()
    })
  })
  $(".design").click(function(){
    $(this).toggle(function(){
      $(".img_1").toggle()
    })
  })
})
// hover effect porfolio
$(document).ready(function(){
  $(".img-port_1").mouseenter(function(){
    $(".del1").show()
  })
  $(".img-port_1").mouseleave(function(){
    $(".del1").hide()
  })
})